### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by wagnst** [kpisacic/Stampar-Peludna-home-assistant-custom-component#1]
Hey, just tried to setup

```
    - platform: stampar_pelud
      name: Pollen Forecast
      station_id: 21
      allergens:
        - 3
        - 6
        - 8
        - 20
        - 90
        - 10
```

but i dont get any sensor created in HA (funnily also no error messages rgd that in the log.
Is this component still working? Havent seen much activity/
